swagger: '2.0'
schemes:
  - https
host: api.communigator.co.uk
basePath: /
info:
  description: |

      # Introduction
      Welcome to the Communigator API! You can use our API to access the Communigator Marketing Suite API endpoints.
      
      We have language bindings in Shell, C#, and PHP! You can view code examples in the dark area to the right, and you can switch the programming language of the examples with the tabs in the top right.
      
      This documentation is still being worked on.

  version: 0.1.1
  title: Communigator API Documentation
  contact:
    email: support@communigator.co.uk
    url: 'https://www.communigator.co.uk/contact-us/'
  #license:
  #  name: Apache 2.0
  #  url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'CommuniGator.png'
#externalDocs:
#  description: Find out how to create Github repo for your OpenAPI spec.
#  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Gator SignOn
    description: Gator Single Signon endpoint
  - name: Gator Mail
    description: GatorMail API endpoint
securityDefinitions:
  client_auth:
    type: oauth2
    tokenUrl: 'https://oauth.communigator.co.uk/core/connect/token'
    flow: application
    scopes:
      'SsoPartnerApi': Allowed to create accounts
  client_application:
    type: oauth2
    flow: password
    tokenUrl: "https://oauth.communigator.co.uk/core/connect/token"
    scopes:
      openId: OpenId scope
      GatorMailApi: GatorMail scope
      offline_access: Offline scope
paths:
  /signon/partner/create:
    post:
      summary: Create Account
      description: This endpoint creates a Single Sign On account and a GatorLeads account. This method is only available to Communigator Partners.
      security:
        - client_auth:
            - SsoPartnerApi
      operationId: signon_create
      tags:
        - Gator SignOn
  /mail/{landingZone}/campaign/{page}/{take}:
    get:
      summary: List all campaigns
      description: Gets Paged List of `Campaign` objects.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getCampaignList
      tags:
        - Gator Mail
  /mail/{landingZone}/campaign:
    post:
      summary: Adds a new campaign
      description: Adds a new campaign
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_addCampaign
      tags:
        - Gator Mail
    patch:
      summary: Updates a campaign
      description: Updates a campaign
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_updateCampaign
      tags:
        - Gator Mail
  /mail/{landingZone}/group:
    post:
      summary: Add a new group
      description: Add a new group
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_addGroup
      tags:
        - Gator Mail
    patch:
      summary: Update a group
      description: Update a group
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_updateGroup
      tags:
        - Gator Mail
  /mail/{landingZone}/group/{groupId}:            
    delete:
      summary: Delete a group
      description: Delete a group
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_deleteGroup
      tags:
        - Gator Mail
  /mail/{landingZone}/group/contact/{contactId}:            
    get:
      summary: Get Groups for Contact
      description: Get Groups for Contact
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_contactGroups
      tags:
        - Gator Mail
  /mail/{landingZone}/group/{groupId}/contact/{contactId}:            
    patch:
      summary: Add contact to a group
      description: Add contact to a group
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_addContactToGroup
      tags:
        - Gator Mail
    delete:
      summary: Remove contact from a group
      description: Remove contact from a group
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_deleteContactFromGroup
      tags:
        - Gator Mail
  /mail/{landingZone}/contact/{email}:
    get:
      summary: List all contacts by email
      description: Gets List of `Email` objects with the supplied email address
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getContactsEmail
      tags:
        - Gator Mail
  /mail/{landingZone}/integration/requests:
    get:
      summary: Get Integration Requests
      description: Returns all requests made by GatorMail users for actions it wishes the integration to perform
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getIntegrationRequests
      tags:
        - Gator Mail
  /mail/{landingZone}/integration/requests/{request}:
    patch:
      summary: Marks a request satisfied.
      description: Marks a request made by a GatorMail user as satisfied.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getIntegrationRequestSatisfied
      tags:
        - Gator Mail
  /mail/{landingZone}/schemamappings:
    get:
      summary: Returns the user generated schema mappings.
      description: Returns the user generated schema mappings. Support is provided though the use of the linkedEntity, entityLinkAttribute, linkedEntityLinkAttribute columns to define a one to one relationship between two entities (e.g contact -> account to retrieve an account name).
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getSchema
      tags:
        - Gator Mail
    delete:
      summary: Clears all schema entities and attributes.
      description: Clears all schema entities and attributes.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_deleteSchema
      tags:
        - Gator Mail
  /mail/{landingZone}/schemamappings/entity:
    post:
      summary: Creates a schema entity record.
      description: Creates a schema entity record.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_postSchemaEntity
      tags:
        - Gator Mail
  /mail/{landingZone}/schemamappings/attribute:
    patch:
      summary: Creates a schema entity attribute record.
      description: Creates a schema entity attribute record.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_postSchemaAttribute
      tags:
        - Gator Mail
  /mail/{landingZone}/datafeed:
    get:
      summary: Returns a batch of data feed records.
      description: Returns a batch of data feed records.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getDatafeed
      tags:
        - Gator Mail
  /mail/{landingZone}/datafeed/{batchIdentifier}:
    patch:
      summary: Marks a feed as processed.
      description: Marks a feed as processed.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getDatafeedBatchIdentifier
      tags:
        - Gator Mail
  /mail/{landingZone}/datafeed/options:
    get:
      summary: Gets the data feed configuration options.
      description: Gets the data feed configuration options.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getDatafeedOptions
      tags:
        - Gator Mail
    post:
      summary: Sets the data feed configuration options.
      description: Sets the data feed configuration options.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_postDatafeedOptions
      tags:
        - Gator Mail
  /mail/{landingZone}/events/{eventId}:
    get:
      summary: Gets event for the given id.
      description: Gets event for the given id.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getEventById
      tags:
        - Gator Mail
  /mail/{landingZone}/events/{page}/{take}:
    get:
      summary: Get all events
      description: Gets all the events
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_getEventPaged
      tags:
        - Gator Mail
  /mail/{landingZone}/events:
    post:
      summary: Creates an event management event
      description: Creates an event management event, associating it with an event entity in the CRM.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_postEvent
      tags:
        - Gator Mail
  /mail/{landingZone}/log/error:
    post:
      summary: Creates error record
      description: Creates an record in the integration error table or updates if a matching error already exists.
      security:
        - client_application:
            - openId
            - GatorMailApi
            - offline_access
      operationId: gatormail_postLogError
      tags:
        - Gator Mail